version: '3.8'

services:
  composer:
    image: composer:2.0
    container_name: kohana_composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs
    depends_on:
      - php

  nginx:
    image: nginx:latest
    container_name: kohana_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: ./
      dockerfile: Dockerfile
    image: kohana_php_image
    container_name: kohana_php
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: kohana_mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
